[package]
name = "eliasfl-chess-gui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
"eliased-chess" = { git = "https://github.com/INDAPlus21/eliased-chess" }